import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { test } from "@/styles";

export default function Home() {
  return <div className={test}></div>;
}
